/**
 * BookNook Product Catalog Data
 * Company: Data Alpha Systems | Intern: Dharla SaiBabu (SaiBabu Dharla)
 * 36+ realistic products across Fiction, Non-Fiction, Children's Books, and Stationery.
 */

const BOOKNOOK_PRODUCTS = [
  // -------------------------------------------------------------
  // FICTION - Literary Fiction
  // -------------------------------------------------------------
  {
    id: "BNK-F-101",
    title: "The Midnight Library",
    author: "Matt Haig",
    category: "Fiction",
    subcategory: "Literary Fiction",
    price: 499,
    originalPrice: 699,
    rating: 4.6,
    reviewsCount: 1420,
    language: "English",
    publisher: "Canongate Books",
    isbn: "978-0525559474",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
    description: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Nora Seed finds herself faced with the possibility of changing her life for a new one.",
    details: "Format: Paperback | Pages: 304 | Dimensions: 12.9 x 1.9 x 19.8 cm",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 24
  },
  {
    id: "BNK-F-102",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    category: "Fiction",
    subcategory: "Literary Fiction",
    price: 550,
    originalPrice: 750,
    rating: 4.4,
    reviewsCount: 890,
    language: "English",
    publisher: "Faber & Faber",
    isbn: "978-0571364886",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "From the bestselling author and Nobel laureate Kazuo Ishiguro comes a thrilling feat of storytelling that explores the meaning of love through the eyes of an unforgettable Artificial Friend.",
    details: "Format: Hardcover | Pages: 320 | Dimensions: 15.3 x 2.8 x 23.4 cm",
    isBestseller: false,
    isNewArrival: true,
    isFeatured: true,
    stockCount: 18
  },
  {
    id: "BNK-F-103",
    title: "Chidambara Rahasyam",
    author: "K. N. Y. Patanjali",
    category: "Fiction",
    subcategory: "Literary Fiction",
    price: 340,
    originalPrice: 450,
    rating: 4.7,
    reviewsCount: 310,
    language: "Telugu",
    publisher: "Visalandhra Publishing House",
    isbn: "978-8178987123",
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80",
    description: "An evocative classic of contemporary Telugu prose delving into social allegories, rural life intricacies, and profound philosophical questions wrapped in lyrical storytelling.",
    details: "Format: Paperback | Pages: 248 | Language: Telugu",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 15
  },

  // -------------------------------------------------------------
  // FICTION - Mystery & Thriller
  // -------------------------------------------------------------
  {
    id: "BNK-F-104",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    category: "Fiction",
    subcategory: "Mystery & Thriller",
    price: 399,
    originalPrice: 599,
    rating: 4.8,
    reviewsCount: 3210,
    language: "English",
    publisher: "Celadon Books",
    isbn: "978-1250301696",
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
    description: "Alicia Berenson’s life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house. Then one evening she shoots her husband five times in the face and never speaks another word.",
    details: "Format: Paperback | Pages: 336 | Dimensions: 13.5 x 2.2 x 20.8 cm",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 40
  },
  {
    id: "BNK-F-105",
    title: "The Maidens",
    author: "Alex Michaelides",
    category: "Fiction",
    subcategory: "Mystery & Thriller",
    price: 450,
    originalPrice: 650,
    rating: 4.2,
    reviewsCount: 1120,
    language: "English",
    publisher: "Orion",
    isbn: "978-1409181729",
    coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80",
    description: "Edward Fosca is a murderer. Of this Mariana is certain. But Fosca is untouchable. A handsome and charismatic Greek Tragedy professor at Cambridge University, Fosca is adored by staff and students alike—particularly by members of a secret society of female students known as The Maidens.",
    details: "Format: Paperback | Pages: 368 | Dimensions: 13.0 x 2.4 x 19.8 cm",
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    stockCount: 22
  },
  {
    id: "BNK-F-106",
    title: "Ponniyin Selvan (Volume 1)",
    author: "Kalki Krishnamurthy",
    category: "Fiction",
    subcategory: "Mystery & Thriller",
    price: 420,
    originalPrice: 550,
    rating: 4.9,
    reviewsCount: 2840,
    language: "Tamil",
    publisher: "Vanathi Pathippakam",
    isbn: "978-8171542116",
    coverImage: "https://images.unsplash.com/photo-1463320726281-696a485928c7?auto=format&fit=crop&w=600&q=80",
    description: "The timeless historical saga detailing royal conspiracy, palace intrigue, assassination attempts, and the thrilling heroics surrounding the ascension of the Chola Empire.",
    details: "Format: Paperback | Pages: 412 | Language: Tamil",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 30
  },

  // -------------------------------------------------------------
  // FICTION - Science Fiction & Fantasy
  // -------------------------------------------------------------
  {
    id: "BNK-F-107",
    title: "Dune",
    author: "Frank Herbert",
    category: "Fiction",
    subcategory: "Science Fiction",
    price: 699,
    originalPrice: 999,
    rating: 4.8,
    reviewsCount: 4500,
    language: "English",
    publisher: "Ace Books",
    isbn: "978-0441013593",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80",
    description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the 'spice' melange.",
    details: "Format: Deluxe Paperback | Pages: 688 | Dimensions: 15.2 x 4.1 x 22.9 cm",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 19
  },
  {
    id: "BNK-F-108",
    title: "Project Hail Mary",
    author: "Andy Weir",
    category: "Fiction",
    subcategory: "Science Fiction",
    price: 580,
    originalPrice: 799,
    rating: 4.9,
    reviewsCount: 2190,
    language: "English",
    publisher: "Ballantine Books",
    isbn: "978-0593135204",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself are doomed. Except right now, he doesn't know that. He can't even remember his own name.",
    details: "Format: Hardcover | Pages: 496 | Dimensions: 16.0 x 3.6 x 24.1 cm",
    isBestseller: false,
    isNewArrival: true,
    isFeatured: true,
    stockCount: 25
  },
  {
    id: "BNK-F-109",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    category: "Fiction",
    subcategory: "Fantasy",
    price: 620,
    originalPrice: 850,
    rating: 4.7,
    reviewsCount: 3820,
    language: "English",
    publisher: "DAW Books",
    isbn: "978-0756404741",
    coverImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80",
    description: "Told in Kvothe's own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen.",
    details: "Format: Paperback | Pages: 662 | Dimensions: 10.7 x 3.8 x 17.5 cm",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 12
  },
  {
    id: "BNK-F-110",
    title: "Godan (गोदान)",
    author: "Munshi Premchand",
    category: "Fiction",
    subcategory: "Literary Fiction",
    price: 260,
    originalPrice: 350,
    rating: 4.9,
    reviewsCount: 1980,
    language: "Hindi",
    publisher: "Rajkamal Prakashan",
    isbn: "978-8126700592",
    coverImage: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80",
    description: "Munshi Premchand's magnum opus detailing the socioeconomic struggles of Indian peasantry, embodying the rural reality of pre-independence India through the life of Hori and Dhania.",
    details: "Format: Paperback | Pages: 384 | Language: Hindi",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 35
  },

  // -------------------------------------------------------------
  // NON-FICTION - Biography & Self-Help
  // -------------------------------------------------------------
  {
    id: "BNK-NF-201",
    title: "Atomic Habits",
    author: "James Clear",
    category: "Non-Fiction",
    subcategory: "Self-Help",
    price: 520,
    originalPrice: 799,
    rating: 4.9,
    reviewsCount: 8900,
    language: "English",
    publisher: "Penguin Random House",
    isbn: "978-0735211292",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    description: "No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that teach you exactly how to form good habits, break bad ones, and master tiny behaviors.",
    details: "Format: Paperback | Pages: 320 | Dimensions: 15.3 x 2.3 x 23.4 cm",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 65
  },
  {
    id: "BNK-NF-202",
    title: "Wings of Fire",
    author: "A. P. J. Abdul Kalam",
    category: "Non-Fiction",
    subcategory: "Biography",
    price: 299,
    originalPrice: 425,
    rating: 4.9,
    reviewsCount: 6100,
    language: "English",
    publisher: "Universities Press",
    isbn: "978-8173711466",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "An inspiring autobiography of former Indian President Dr. A.P.J. Abdul Kalam, detailing his early humble childhood in Rameswaram, his career in ISRO/DRDO, and his vision for India's technological ascendancy.",
    details: "Format: Paperback | Pages: 180 | Dimensions: 14.0 x 1.3 x 21.6 cm",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 50
  },
  {
    id: "BNK-NF-203",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    category: "Non-Fiction",
    subcategory: "Biography",
    price: 699,
    originalPrice: 999,
    rating: 4.7,
    reviewsCount: 2450,
    language: "English",
    publisher: "Simon & Schuster",
    isbn: "978-1451648539",
    coverImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80",
    description: "Based on more than forty interviews with Steve Jobs conducted over two years—as well as interviews with more than a hundred family members, friends, adversaries, competitors, and colleagues—Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur.",
    details: "Format: Hardcover | Pages: 656 | Dimensions: 15.9 x 4.6 x 23.8 cm",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 16
  },
  {
    id: "BNK-NF-204",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Non-Fiction",
    subcategory: "Business & Finance",
    price: 360,
    originalPrice: 499,
    rating: 4.8,
    reviewsCount: 5400,
    language: "English",
    publisher: "Harriman House",
    isbn: "978-9390166268",
    coverImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=600&q=80",
    description: "Doing well with money isn't necessarily about what you know. It's about how you behave. And behavior is hard to teach, even to really smart people. 19 short stories exploring the strange ways people think about money.",
    details: "Format: Paperback | Pages: 252 | Dimensions: 13.0 x 2.0 x 19.8 cm",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 45
  },
  {
    id: "BNK-NF-205",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
    subcategory: "History",
    price: 599,
    originalPrice: 899,
    rating: 4.8,
    reviewsCount: 7120,
    language: "English",
    publisher: "Vintage Books",
    isbn: "978-0099590088",
    coverImage: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=600&q=80",
    description: "100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us. Homo sapiens. How did our species succeed in the battle for dominance? An international publishing phenomenon.",
    details: "Format: Paperback | Pages: 512 | Dimensions: 12.9 x 3.3 x 19.8 cm",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 38
  },
  {
    id: "BNK-NF-206",
    title: "Astrophysics for People in a Hurry",
    author: "Neil deGrasse Tyson",
    category: "Non-Fiction",
    subcategory: "Science",
    price: 430,
    originalPrice: 599,
    rating: 4.6,
    reviewsCount: 1820,
    language: "English",
    publisher: "W. W. Norton & Company",
    isbn: "978-0393609394",
    coverImage: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80",
    description: "What is the nature of space and time? How do we fit within the universe? How does the universe fit within us? There's no better guide through these mind-expanding questions than acclaimed astrophysicist Neil deGrasse Tyson.",
    details: "Format: Hardcover | Pages: 224 | Dimensions: 11.4 x 2.3 x 19.3 cm",
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    stockCount: 20
  },
  {
    id: "BNK-NF-207",
    title: "Veyipadagalu (వేయిపడగలు)",
    author: "Viswanatha Satyanarayana",
    category: "Non-Fiction",
    subcategory: "History",
    price: 780,
    originalPrice: 950,
    rating: 4.9,
    reviewsCount: 650,
    language: "Telugu",
    publisher: "Viswanatha Publications",
    isbn: "978-8178984431",
    coverImage: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
    description: "Epic cultural chronicle by Jnanpith awardee Viswanatha Satyanarayana portraying Indian ethos, societal shifts, and cultural heritage spanning several generations in Andhra Pradesh.",
    details: "Format: Hardcover | Pages: 880 | Language: Telugu",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 10
  },
  {
    id: "BNK-NF-208",
    title: "Madhavikutty: Ente Katha",
    author: "Kamala Das",
    category: "Non-Fiction",
    subcategory: "Biography",
    price: 310,
    originalPrice: 420,
    rating: 4.7,
    reviewsCount: 880,
    language: "Tamil",
    publisher: "Kizhakku Pathippagam",
    isbn: "978-8184931201",
    coverImage: "https://images.unsplash.com/photo-1491841573634-28140fc7ced7?auto=format&fit=crop&w=600&q=80",
    description: "The unapologetic, deeply moving personal memoirs of iconic literary rebel Kamala Das, translated with poetic nuance exploring feminine desire, art, and societal taboos.",
    details: "Format: Paperback | Pages: 208 | Language: Tamil",
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    stockCount: 14
  },

  // -------------------------------------------------------------
  // CHILDREN'S BOOKS
  // -------------------------------------------------------------
  {
    id: "BNK-CB-301",
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    category: "Children's Books",
    subcategory: "Picture Books",
    price: 380,
    originalPrice: 499,
    rating: 4.9,
    reviewsCount: 3800,
    language: "English",
    publisher: "Puffin Books",
    isbn: "978-0140569322",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "The all-time classic picture book, from generation to generation, sold somewhere in the world every 30 seconds! A timeless story that satisfies a child's natural appetite for discovery.",
    details: "Format: Board Book | Pages: 32 | Dimensions: 18.0 x 1.4 x 13.0 cm",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 50
  },
  {
    id: "BNK-CB-302",
    title: "Malgudi Days for Young Readers",
    author: "R. K. Narayan",
    category: "Children's Books",
    subcategory: "Story Books",
    price: 280,
    originalPrice: 399,
    rating: 4.8,
    reviewsCount: 1940,
    language: "English",
    publisher: "Indian Thought Publications",
    isbn: "978-8185986173",
    coverImage: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=600&q=80",
    description: "Delightful short stories capturing the endearing adventures of Swami and his companions in the fictional town of Malgudi, rich in humor and innocent childhood nostalgia.",
    details: "Format: Paperback | Pages: 264 | Dimensions: 13.2 x 1.6 x 19.8 cm",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 28
  },
  {
    id: "BNK-CB-303",
    title: "Grandma's Bag of Stories",
    author: "Sudha Murty",
    category: "Children's Books",
    subcategory: "Story Books",
    price: 240,
    originalPrice: 350,
    rating: 4.9,
    reviewsCount: 4200,
    language: "English",
    publisher: "Puffin Books India",
    isbn: "978-0143333623",
    coverImage: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80",
    description: "Memories of a grandmother spinning tales over hot cups of cocoa and mangoes in summer. Filled with delightful animals, clever kings, tricky bears, and kind fairies that impart wholesome values.",
    details: "Format: Paperback | Pages: 176 | Dimensions: 13.9 x 1.3 x 19.8 cm",
    isBestseller: true,
    isNewArrival: true,
    isFeatured: true,
    stockCount: 60
  },
  {
    id: "BNK-CB-304",
    title: "Panchatantra Ki Kahaniya (पंचतंत्र)",
    author: "Vishnu Sharma",
    category: "Children's Books",
    subcategory: "Educational Books",
    price: 220,
    originalPrice: 299,
    rating: 4.7,
    reviewsCount: 1540,
    language: "Hindi",
    publisher: "Manoj Publications",
    isbn: "978-8181335221",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Timeless moral animal fables from ancient India, illustrated in vibrant colors to introduce young learners to practical wisdom, strategy, and empathy.",
    details: "Format: Paperback | Pages: 160 | Language: Hindi",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 30
  },
  {
    id: "BNK-CB-305",
    title: "The Ultimate Science & Space Activity Book",
    author: "National Geographic Kids",
    category: "Children's Books",
    subcategory: "Activity Books",
    price: 450,
    originalPrice: 599,
    rating: 4.8,
    reviewsCount: 920,
    language: "English",
    publisher: "National Geographic",
    isbn: "978-1426338144",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    description: "Bursting with mazes, sticker challenges, connect-the-dots constellations, and hands-on kitchen experiments that bring astrophysics and paleontology alive for curious young minds.",
    details: "Format: Paperback | Pages: 112 | Illustrated Full-Color",
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    stockCount: 20
  },
  {
    id: "BNK-CB-306",
    title: "First 100 Words Board Book",
    author: "Roger Priddy",
    category: "Children's Books",
    subcategory: "Board Books",
    price: 320,
    originalPrice: 420,
    rating: 4.6,
    reviewsCount: 2100,
    language: "English",
    publisher: "Priddy Books",
    isbn: "978-0312510787",
    coverImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
    description: "An ideal early learning tool with padded covers, rounded corners, and bright photography categorized into animals, toys, food, and familiar household things.",
    details: "Format: Board Book | Pages: 26 | Dimensions: 15.6 x 2.4 x 15.6 cm",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 42
  },

  // -------------------------------------------------------------
  // STATIONERY - Notebooks & Journals
  // -------------------------------------------------------------
  {
    id: "BNK-ST-401",
    title: "Artisan Leatherbound Journal (Handmade 240 GSM)",
    author: "BookNook Atelier",
    category: "Stationery",
    subcategory: "Notebooks & Journals",
    price: 890,
    originalPrice: 1299,
    rating: 4.9,
    reviewsCount: 780,
    language: "English",
    publisher: "BookNook Handcrafts",
    isbn: "BNK-NB-001",
    coverImage: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80",
    description: "Exquisite full-grain buffalo leather journal equipped with deckle-edge unruled cotton rag paper. Ideal for fountain pens, watercolor washes, and personal journaling.",
    details: "200 Deckle-Edge Pages | 240 GSM Bleed-Proof Cotton Paper | Brass C-Clasp Closure",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 22
  },
  {
    id: "BNK-ST-402",
    title: "Hardcover Dotted Bullet Journal (Sage Green)",
    author: "Nordic Paper Co.",
    category: "Stationery",
    subcategory: "Notebooks & Journals",
    price: 540,
    originalPrice: 750,
    rating: 4.7,
    reviewsCount: 1150,
    language: "English",
    publisher: "Nordic Paper Co.",
    isbn: "BNK-NB-002",
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
    description: "A5 hardcover journal with 160 numbered pages of 120 GSM bamboo paper, dual silk bookmarks, back expandable pocket, and elastic closure band.",
    details: "Format: A5 Hardcover | 160 Pages | 120 GSM Dot Grid | Pen Loop Included",
    isBestseller: true,
    isNewArrival: true,
    isFeatured: true,
    stockCount: 35
  },
  {
    id: "BNK-ST-403",
    title: "Pocket Minimalist Kraft Notebooks (Set of 3)",
    author: "Craft & Quill",
    category: "Stationery",
    subcategory: "Notebooks & Journals",
    price: 260,
    originalPrice: 350,
    rating: 4.5,
    reviewsCount: 420,
    language: "English",
    publisher: "Craft & Quill",
    isbn: "BNK-NB-003",
    coverImage: "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=600&q=80",
    description: "Compact 3.5 x 5.5 inch stitched kraft notebooks. Contains plain, ruled, and gridded books made from 100% recycled acid-free archival fibers.",
    details: "Pack of 3 Pocket Notebooks | 64 Pages Each | Saddle Stitched Binding",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 48
  },

  // -------------------------------------------------------------
  // STATIONERY - Pens & Pencils
  // -------------------------------------------------------------
  {
    id: "BNK-ST-404",
    title: "Vintage Brass Fountain Pen with Fine Iridium Nib",
    author: "Heritage Penmakers",
    category: "Stationery",
    subcategory: "Pens & Pencils",
    price: 1250,
    originalPrice: 1800,
    rating: 4.8,
    reviewsCount: 560,
    language: "English",
    publisher: "Heritage Pen Co.",
    isbn: "BNK-PEN-001",
    coverImage: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80",
    description: "Machined from solid raw brass that develops an authentic personalized patina over years of writing. Fitted with a German-engineered fine nib and includes an ink piston converter.",
    details: "Weight: 45g Solid Brass | Fine 0.5mm Nib | Cartridge & Converter Compatible",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 15
  },
  {
    id: "BNK-ST-405",
    title: "Japanese Fine Gel Pens (0.5mm, 10 Muted Earth Tones)",
    author: "Sakura Ink Studios",
    category: "Stationery",
    subcategory: "Pens & Pencils",
    price: 480,
    originalPrice: 650,
    rating: 4.8,
    reviewsCount: 2310,
    language: "English",
    publisher: "Sakura Ink Studios",
    isbn: "BNK-PEN-002",
    coverImage: "https://images.unsplash.com/photo-1585336261026-7f0980bb2912?auto=format&fit=crop&w=600&q=80",
    description: "Quick-drying, smear-proof gel ink pens in soothing vintage shades: Matcha green, terracotta, navy blue, dusty pink, smoked amber, and warm charcoal.",
    details: "10 Pens Pack | 0.5mm Japanese Ceramic Needle Tip | Waterproof Pigment",
    isBestseller: true,
    isNewArrival: true,
    isFeatured: false,
    stockCount: 55
  },
  {
    id: "BNK-ST-406",
    title: "Graded Graphite Artist Sketching Pencils (Set of 12)",
    author: "Derwent Craft",
    category: "Stationery",
    subcategory: "Pens & Pencils",
    price: 399,
    originalPrice: 550,
    rating: 4.6,
    reviewsCount: 710,
    language: "English",
    publisher: "Derwent Fine Arts",
    isbn: "BNK-PEN-003",
    coverImage: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=600&q=80",
    description: "Premium cedar wood pencils ranging from ultra-hard 4H to velvet deep 8B. Highly break-resistant and perfect for shading, portraits, and drafting.",
    details: "Set of 12 Metal Tin Pencils | Grades 4H to 8B | SV Bonded Core",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 30
  },

  // -------------------------------------------------------------
  // STATIONERY - Art Supplies
  // -------------------------------------------------------------
  {
    id: "BNK-ST-407",
    title: "Botanical Watercolor Travel Pocket Palette (24 Half-Pans)",
    author: "Montmartre Arts",
    category: "Stationery",
    subcategory: "Art Supplies",
    price: 1190,
    originalPrice: 1650,
    rating: 4.9,
    reviewsCount: 640,
    language: "English",
    publisher: "Montmartre Fine Arts",
    isbn: "BNK-ART-001",
    coverImage: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80",
    description: "Professional grade artist watercolours enriched with natural gum Arabic. Comes in a sturdy metal travel box with foldable mixing wells, water brush pen, and sponge.",
    details: "24 Vibrant Lightfast Pigments | Travel Metal Tin | Includes Water Reservoir Brush",
    isBestseller: false,
    isNewArrival: true,
    isFeatured: true,
    stockCount: 16
  },
  {
    id: "BNK-ST-408",
    title: "Cold-Pressed 300 GSM Watercolor Block (100% Cotton)",
    author: "Arches Legacy",
    category: "Stationery",
    subcategory: "Art Supplies",
    price: 850,
    originalPrice: 1150,
    rating: 4.7,
    reviewsCount: 430,
    language: "English",
    publisher: "Arches Paper Mills",
    isbn: "BNK-ART-002",
    coverImage: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=600&q=80",
    description: "Glue-bound on all four edges to avoid paper buckling during heavy washes. Natural gelatin sized with uniform grain texture suited for wet-on-wet technique.",
    details: "Size: 20x20 cm | 20 Sheets | 300 GSM 100% Cotton Rag | Acid-Free",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 18
  },

  // -------------------------------------------------------------
  // STATIONERY - Desk Accessories
  // -------------------------------------------------------------
  {
    id: "BNK-ST-409",
    title: "Solid Walnut Wood Book Stand & Tablet Easel",
    author: "Timber & Craft",
    category: "Stationery",
    subcategory: "Desk Accessories",
    price: 980,
    originalPrice: 1450,
    rating: 4.8,
    reviewsCount: 890,
    language: "English",
    publisher: "Timber & Craft Studio",
    isbn: "BNK-DSK-001",
    coverImage: "https://images.unsplash.com/photo-1544717302-de2939b7ef71?auto=format&fit=crop&w=600&q=80",
    description: "Ergonomic adjustable reading stand crafted from certified American walnut. Features spring-loaded brass page holders to support thick textbooks and cookbooks hands-free.",
    details: "5 Angle Adjustment Tilts | Fold-Flat Portable Design | Anti-Slip Silicone Base",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: true,
    stockCount: 20
  },
  {
    id: "BNK-ST-410",
    title: "Heavy Cast-Brass Owl Bookends (Pair)",
    author: "Antiqua Atelier",
    category: "Stationery",
    subcategory: "Desk Accessories",
    price: 1450,
    originalPrice: 2100,
    rating: 4.9,
    reviewsCount: 340,
    language: "English",
    publisher: "Antiqua Atelier",
    isbn: "BNK-DSK-002",
    coverImage: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=600&q=80",
    description: "Heirloom-grade bookends sculpted with intricate owl feathers symbolizing wisdom. Weighted at 1.8 kg to firmly support encyclopedia volumes on study shelves.",
    details: "Set of 2 Heavy Brass Bookends | Weighted Velvet-Padded Bottoms | Height: 18 cm",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 12
  },
  {
    id: "BNK-ST-411",
    title: "Engraved Brass Bookmark Ruler with Silk Tassel",
    author: "BookNook Atelier",
    category: "Stationery",
    subcategory: "Desk Accessories",
    price: 299,
    originalPrice: 450,
    rating: 4.6,
    reviewsCount: 980,
    language: "English",
    publisher: "BookNook Handcrafts",
    isbn: "BNK-DSK-003",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Slender 15 cm brass ruler laser-engraved with vintage botanical motifs and inspirational literary quotes. Adorned with a hand-spun emerald green silk tassel.",
    details: "Pure Polished Brass | 15cm Dual Metric & Imperial Markings | Velvet Gift Pouch",
    isBestseller: true,
    isNewArrival: true,
    isFeatured: false,
    stockCount: 45
  },

  // -------------------------------------------------------------
  // STATIONERY - Gift Sets
  // -------------------------------------------------------------
  {
    id: "BNK-ST-412",
    title: "Bibliophile Luxury Gift Hamper (Journal, Brass Pen & Candle)",
    author: "BookNook Signature",
    category: "Stationery",
    subcategory: "Gift Sets",
    price: 1850,
    originalPrice: 2600,
    rating: 5.0,
    reviewsCount: 410,
    language: "English",
    publisher: "BookNook Signature",
    isbn: "BNK-GFT-001",
    coverImage: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80",
    description: "The ultimate curated gift for avid readers and writers. Includes an embossed hardcover journal, brass twist pen, soy-wax 'Old Books & Mahogany' scented candle, and woven linen bookmark.",
    details: "Includes: Hardcover Journal + Brass Pen + 200g Scented Soy Candle + Gold Foil Gift Box",
    isBestseller: true,
    isNewArrival: true,
    isFeatured: true,
    stockCount: 14
  },
  {
    id: "BNK-ST-413",
    title: "Wax Seal Stamp Kit with Melting Spoon & Metallic Beads",
    author: "Medieval Scribe Co.",
    category: "Stationery",
    subcategory: "Gift Sets",
    price: 790,
    originalPrice: 1100,
    rating: 4.7,
    reviewsCount: 520,
    language: "English",
    publisher: "Medieval Scribe Co.",
    isbn: "BNK-GFT-002",
    coverImage: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80",
    description: "Recreate the charm of correspondence with this complete wax sealing set featuring a brass 'Tree of Life' stamp, wooden handle, melting furnace spoon, and 200 octagonal wax beads.",
    details: "Brass Stamp + Rosewood Handle + Melting Spoon + Tea Candles + 200 Wax Beads",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 25
  },

  // -------------------------------------------------------------
  // ADDITIONAL MULTI-LANGUAGE & SPECIAL TITLES
  // -------------------------------------------------------------
  {
    id: "BNK-F-111",
    title: "Barrister Parvatheesam (బారిష్టర్ పార్వతీశం)",
    author: "Mokkapati Narasimha Sastry",
    category: "Fiction",
    subcategory: "Literary Fiction",
    price: 320,
    originalPrice: 420,
    rating: 4.8,
    reviewsCount: 1120,
    language: "Telugu",
    publisher: "Jayanti Publications",
    isbn: "978-8178983204",
    coverImage: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80",
    description: "A hilarious and heartwarming Telugu classic satirizing the adventures of an orthodox young man traveling from a quiet Godavari village to study law in Victorian London.",
    details: "Format: Paperback | Pages: 280 | Language: Telugu",
    isBestseller: false,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 20
  },
  {
    id: "BNK-NF-209",
    title: "Raag Darbari (राग दरबारी)",
    author: "Shrilal Shukla",
    category: "Fiction",
    subcategory: "Literary Fiction",
    price: 350,
    originalPrice: 480,
    rating: 4.8,
    reviewsCount: 1650,
    language: "Hindi",
    publisher: "Rajkamal Prakashan",
    isbn: "978-8126701834",
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80",
    description: "A monumental Sahitya Akademi award-winning satirical Hindi novel dissecting rural Indian politics, nepotism, and societal absurdities with biting wit.",
    details: "Format: Paperback | Pages: 342 | Language: Hindi",
    isBestseller: false,
    isNewArrival: true,
    isFeatured: false,
    stockCount: 18
  },
  {
    id: "BNK-F-112",
    title: "Sivagamiyin Sabatham",
    author: "Kalki Krishnamurthy",
    category: "Fiction",
    subcategory: "Mystery & Thriller",
    price: 490,
    originalPrice: 650,
    rating: 4.9,
    reviewsCount: 1780,
    language: "Tamil",
    publisher: "Alliance Company",
    isbn: "978-8184931898",
    coverImage: "https://images.unsplash.com/photo-1463320726281-696a485928c7?auto=format&fit=crop&w=600&q=80",
    description: "An epic Tamil historical romance and conflict novel centered around the Pallava empire, the Chalukyan invasion, Bharatanatyam maestro Sivagami, and Prince Narasimhavarman.",
    details: "Format: Hardcover | Pages: 520 | Language: Tamil",
    isBestseller: true,
    isNewArrival: false,
    isFeatured: false,
    stockCount: 22
  }
];

// Helper to query catalog
const BookNookDB = {
  getAll: () => BOOKNOOK_PRODUCTS,
  getById: (id) => BOOKNOOK_PRODUCTS.find(item => item.id === id),
  getByCategory: (category) => BOOKNOOK_PRODUCTS.filter(item => item.category.toLowerCase() === category.toLowerCase()),
  getFeatured: () => BOOKNOOK_PRODUCTS.filter(item => item.isFeatured),
  getBestsellers: () => BOOKNOOK_PRODUCTS.filter(item => item.isBestseller),
  getNewArrivals: () => BOOKNOOK_PRODUCTS.filter(item => item.isNewArrival),
  getStationery: () => BOOKNOOK_PRODUCTS.filter(item => item.category === "Stationery"),
  getRelated: (product, limit = 4) => {
    if (!product) return [];
    return BOOKNOOK_PRODUCTS.filter(item => 
      item.id !== product.id && 
      (item.category === product.category || item.subcategory === product.subcategory)
    ).slice(0, limit);
  },
  getAuthors: () => {
    const set = new Set(BOOKNOOK_PRODUCTS.map(p => p.author));
    return Array.from(set).sort();
  },
  getCategories: () => ["Fiction", "Non-Fiction", "Children's Books", "Stationery"],
  getLanguages: () => ["English", "Telugu", "Hindi", "Tamil"]
};

